
server:
  port: 9001
  tomcat:
    connection-timeout: 2s #temps max entre l'établissement de la connexion TCP avec un client et la réception de la 1ere req http
    keep-alive-timeout: 15s #durée max d'ouverture de la connexion pour attendre de nouvelles requêtes http
    threads:
      max: 50 #nb max de threads dans le pool - au-delà, les requêtes http sont mises en pool
      min-spare: 5  #nb min de thread toujours presents dans le pool, donc créés au démarrage
  #shutdown déclenché quand un SIGTERM est reçu par le serveur
  shutdown: graceful # défaut immediate - graceful : plus de cnx entrante / finalisation du traitement des req en cours / arrêt des ressources
spring:
  application:
    name: catalog-service # utilisée par le config-server pour filtrer/retrouver la configuration destinée à cette application
  # temps max pour que l'application Spring complète un graceful shutdown
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 #temps max pour recevoir un obj Connection depuis le pool
      maximum-pool-size: 5

polar:
  greeting: "Welcome to the local book catalog !"
